name: value_linking
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.11
  - pip
  - openjdk=21
  - maven
  - spacy-model-en_core_web_sm
  - pip:
    - accelerate==1.10.1
    - pandas==2.3.3
    - scikit-learn==1.7.2
    - scipy==1.16.2
    - matplotlib==3.10.7
    - sqlalchemy==2.0.36
    - pyyaml==6.0.3
    - requests==2.32.5
    - tqdm==4.66.5
    - setuptools==79.0.1
    - packaging==25.0
    - numpy==1.26.4
    - chardet==5.2.0
    - dashscope==1.24.1
    - datasets==2.21.0
    - datasketch==1.6.5
    - func_timeout==4.3.5
    - google_cloud_aiplatform==1.107.0
    - huggingface_hub==0.34.4
    - ijson==3.4.0
    - json_repair==0.52.0
    - jsonlines==4.0.0
    - langchain==0.3.27
    - langchain_chroma==0.2.6
    - langchain_community==0.3.31
    - langchain_core==0.3.79
    - langchain_openai==0.3.35
    - langgraph==0.6.10
    - more_itertools==10.8.0
    - openai==2.3.0
    - orjson==3.11.3
    - peft==0.12.0
    - protobuf==4.25.5
    - pydantic==2.12.2
    - pyserini==1.2.0
    - python-dotenv==1.1.1
    - rapidfuzz==3.14.1
    - ray==2.48.0
    - sentence_transformers==2.7.0
    - spellchecker==0.4
    - sqlglot==26.24.0
    - sqlvalidator==0.0.20
    - faiss-gpu-cu12==1.11.0
    - tabulate==0.9.0
    - torch==2.8.0
    - transformers==4.56.0
    - trl==0.8.6
    - vllm==0.10.2
    - wandb==0.21.4
    - loguru==0.7.2
    - nltk==3.9.1
    - spacy==3.7.5